---
- name: Add Jenkins-CI Repository Key
  apt_key:
    url: "http://pkg.jenkins-ci.org/{{ ansible_os_family|lower }}/jenkins-ci.org.key"
    state: present

- name: Add Jenkins-CI Repository
  apt_repository:
    repo: 'deb http://pkg.jenkins-ci.org/{{ ansible_os_family|lower }} binary/'
    state: present
    update_cache: yes

- name: Install Jenkins-CI
  apt:
    name: jenkins
    state: present
    update_cache: yes
    cache_valid_time: 600
  notify:
    - Restart Jenkins
  register: install_jenkins

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
  notify: Restart Jenkins

- name: Set Jenkins-CI to listen only on 127.0.0.1
  lineinfile:
    dest: /etc/default/jenkins
    regexp: ^JENKINS_ARGS=
    line: 'JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"'
  notify: Restart Jenkins
  tags:
    - jenkins-conf

- name: Enable Jenkins-CI Permissive Script Plugin
  lineinfile:
    dest: /etc/default/jenkins
    regexp: ^JAVA_ARGS=
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Dpermissive-script-security.enabled=true"'
  notify: Restart Jenkins
  tags:
    - jenkins-conf

- name: Create backup directory
  file:
    path: "{{ jenkins_backup_directory }}"
    owner: jenkins
    group: jenkins
    mode: '0755'
    state: directory

- name: Copy backup script
  template:
    src: "jenkins-backup.sh.j2"
    dest: "/usr/local/bin/jenkins-backup.sh"
    mode: "0755"

- name: Create cron job for jenkins-backup script
  cron:
    name: Backup jenkins
    user: root
    job: "/usr/bin/flock -w 10 /var/lock/backup_jenkins.lock /usr/local/bin/jenkins-backup.sh > /dev/null 2>&1"
    minute: "*/15"
    cron_file: jenkins_backup

- name: Prep ssh private key placement
  file:
    path: "{{ jenkins_home }}/.ssh"
    mode: '0711'
    owner: jenkins
    group: jenkins
    state: directory

- name: Place ssh deploy key
  shell: |
    aws ssm get-parameter --with-decryption --name {{ ssm_key }} --output text --query Parameter.Value --region us-west-2 > {{ jenkins_home }}/.ssh/id_rsa
    chown jenkins.jenkins {{ jenkins_ssh_key }}
    chmod 0400 {{ jenkins_ssh_key }}
  become: yes


- name: Place ssh config
  template:
    src: "ssh-config.j2"
    dest: "{{ jenkins_home }}/.ssh"
    owner: jenkins
    group: jenkins
    mode: 0600
