---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  become_user: root

- name: restart prometheus node exporter
  service:
    name: prometheus-node-exporter
    state: restarted
  become_user: root

